name: easy_assets
description: "A Flutter package for easy asset management and loading"
version: 0.0.1
homepage: https://github.com/VEMUC001/easy_assets/tree/main
license: MIT

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.0
  yaml: ^3.1.2
  args: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.25.7
  mocktail: ^1.0.4
  coverage: ^1.9.2

executables:
  easy_assets_generator: easy_assets_generator
